# Read csv file

In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv('Data.csv')

In [3]:
df

,SYMBOL,SERIES,DATE1,PREV_CLOSE,OPEN_PRICE,HIGH_PRICE,LOW_PRICE,LAST_PRICE,CLOSE_PRICE,AVG_PRICE,TTL_TRD_QNTY,TURNOVER_LACS,NO_OF_TRADES,DELIV_QTY,DELIV_PER
0,20MICRONS,EQ,12-Aug-2022,105.65,106.00,110.75,104.65,104.65,105.65,107.46,418253,449.47,6462,168909,40.38
1,21STCENMGM,EQ,12-Aug-2022,25.70,26.00,26.00,25.20,25.20,25.50,25.45,28312,7.20,93,23676,83.63
2,3IINFOLTD,EQ,12-Aug-2022,40.85,40.90,41.45,40.50,40.75,40.70,40.87,250974,102.58,2564,159693,63.63
3,3MINDIA,EQ,12-Aug-2022,22726.80,22799.00,23000.00,22241.50,22490.00,22470.05,22644.87,6132,1388.58,3174,2620,42.73
4,3PLAND,EQ,12-Aug-2022,15.60,15.55,16.00,15.10,15.90,15.90,15.23,7894,1.20,40,7442,94.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2230,ZOTA,EQ,12-Aug-2022,273.55,276.40,278.00,272.00,275.00,276.15,273.83,17875,48.95,291,9095,50.88
2231,ZUARI,EQ,12-Aug-2022,158.80,160.00,163.00,156.20,158.00,158.25,157.77,175881,277.49,3389,108519,61.7
2232,ZUARIIND,EQ,12-Aug-2022,162.00,164.50,167.00,160.00,160.00,162.20,163.40,44330,72.43,1092,25702,57.98
2233,ZYDUSLIFE,EQ,12-Aug-2022,381.70,383.75,388.50,380.45,386.70,386.85,384.72,4788229,18421.33,54049,1752970,36.61
2234,ZYDUSWELL,EQ,12-Aug-2022,1626.00,1611.20,1634.15,1600.15,1600.15,1605.55,1608.41,13840,222.60,2065,7705,55.67

In [4]:
df['SYMBOL'].dtype

dtype('O')

In [5]:
print(df['SYMBOL'].dtype)

object

In [8]:
print(df['PREV_CLOSE'])

0         105.65
1          25.70
2          40.85
3       22726.80
4          15.60
          ...
2230      273.55
2231      158.80
2232      162.00
2233      381.70
2234     1626.00
Name: PREV_CLOSE, Length: 2235, dtype: float64

In [9]:
print(df['PREV_CLOSE'].astype('category'))

0         105.65
1          25.70
2          40.85
3       22726.80
4          15.60
          ...
2230      273.55
2231      158.80
2232      162.00
2233      381.70
2234     1626.00
Name: PREV_CLOSE, Length: 2235, dtype: category
Categories (2033, float64): [0.55, 0.80, 0.90, 0.95, ..., 22726.8, 40584.1, 49011.1, 82500.7]

C:\Users\avima\AppData\Local\Temp\ipykernel_3676\1744644861.py:1: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  print(df['PREV_CLOSE'].astype('category'))